In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:
import numpy as np
import pickle
import torch
from torch import nn, from_numpy
from torch.optim import Adam
from sklearn.utils import shuffle
from torch.utils.data import TensorDataset, DataLoader
from torchvision import datasets, transforms

In [17]:
X_train,X_test,y_train,y_test = pickle.load(open('/content/drive/My Drive/ML_Fundamentals/nn/fashion_mnist.p','rb'))

#Q6.1a

In [18]:
784*128 + 128 + 128*10 + 10

101770

In [19]:
X_train = from_numpy(X_train)
X_test = from_numpy(X_test)
y_train = from_numpy(y_train)
y_test = from_numpy(y_test)

#Q6.1b

In [20]:
inputlayer = 784
nodes1 = 128
linearlayer = 10

firstlayerp = (inputlayer + 1) * nodes1

secondlayerp = (nodes1 + 1) * linearlayer

totalp = firstlayerp + secondlayerp

model = nn.Sequential(
    nn.Linear(784, 128),
    nn.ReLU(),
    nn.Linear(128, 10)
)
loss_function = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters())

In [21]:
n_iter = 150

for t in range(n_iter):
    print('Running iteration ' + str(t))
    y_pred = model(X_train)

    # Forward pass
    print(model(X_train[0]))
    loss = loss_function(y_pred, y_train)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print('In-sample cross-entropy: ' + str(loss.item()))

y_pred = model(X_test)
print('Out-of-sample accuracy: ' + str((y_pred.argmax(1) == y_test).sum().item() / 10000))

Running iteration 0
tensor([ 55.4926,   6.1672, -16.5618, -91.5125, -43.3567,  78.8064,  13.0171,
          5.0914, -11.5786, -32.7503], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 45.314395904541016
Running iteration 1
tensor([-187.9245,   50.7863,   30.9413,  -46.7739,    2.0743,   45.2676,
          -4.5318,    4.2592,   15.9939,  -42.0114], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 37.370628356933594
Running iteration 2
tensor([-258.6617,  -16.3222,   39.7775,   36.7350,  -70.7463,   43.1977,
          15.5339,  -16.9354,   51.3915,    5.1645], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 39.89422607421875
Running iteration 3
tensor([-279.6080,  -18.3967,   28.6333,   -6.7949,  -66.9560,   31.4858,
          38.0102,   -8.8685,   62.2941,   15.1713], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 38.56993103027344
Running iteration 4
tensor([-273.7401,  -27.0489,   29.6273,  -29.2530,  -38.3276,   25.2613,
          28.0368,   17.1436,   60.0937,   10.3437], g

#Q6.1c

In [22]:
784*128 + 128 + 128*32 + 32 + 32*10 + 10

104938

#Q6.1d

In [23]:
model = nn.Sequential(
    nn.Linear(784, 128),
    nn.ReLU(),
    nn.Linear(128, 32),
    nn.ReLU(),
    nn.Linear(32, 10)
)
loss_function = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters())

n_iter = 150

for t in range(n_iter):
    print('Running iteration ' + str(t))
    y_pred = model(X_train)

    # Forward pass
    print(model(X_train[0]))
    loss = loss_function(y_pred, y_train)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print('In-sample cross-entropy: ' + str(loss.item()))

y_pred = model(X_test)
print('Out-of-sample accuracy: ' + str((y_pred.argmax(1) == y_test).sum().item() / 10000))

Running iteration 0
tensor([-11.7971, -23.4996,  28.7122,  10.2332,  24.9544,   9.3193,   7.7587,
         -4.5174,  -0.7470,   2.4395], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 14.170170783996582
Running iteration 1
tensor([  3.4265, -20.1839, -22.1424,  23.2528,  -2.3028,   2.7595,   4.3468,
         12.6520, -14.0573,  30.8253], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 15.739051818847656
Running iteration 2
tensor([ 12.7175, -13.6288, -25.6871,   5.4498,   2.8222,   5.9993,  -0.0305,
          9.0343, -15.7913,   4.7856], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 9.071403503417969
Running iteration 3
tensor([ -2.8494, -10.2476, -13.1499,   2.7876,  21.2800,  -1.0041,   7.8875,
         13.7664,  -1.1450,   4.2396], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 7.831035614013672
Running iteration 4
tensor([-1.1927, -5.5464, -8.5133,  3.7389, 15.2367,  0.7483,  5.9148,  7.7223,
         4.6708,  0.2865], grad_fn=<ViewBackward0>)
In-sample cross-entropy: 5

We see the accuracy has increased by approximately 3% for same number of iterations.

#Q6.2

In [24]:
X_train = np.reshape(X_train, (60000,1,28,28))
X_test  = np.reshape(X_test, (10000,1,28,28))

X_train_tensor = X_train
X_test_tensor = X_test
y_train_tensor = y_train
y_test_tensor = y_test



#Q6.2a

In [25]:
model = nn.Sequential(nn.Conv2d(1,40,6),
        nn.ReLU(),
        nn.Flatten(),
        nn.Linear(40*23*23,10))
loss_function = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters())

n_epochs = 20
batch_size = 1000
for epoch in range(n_epochs):
    print('Running epoch ' + str(epoch))
    X_train_tensor, y_train_tensor = shuffle(X_train_tensor, y_train_tensor)

    # Ea. cycle is a loop through all the batches:
    for batch in range(int(60000/batch_size)):

        # ForwardProp
        y_pred = model(X_train_tensor[batch*batch_size:(batch+1)*batch_size])
        loss = loss_function(y_pred, y_train_tensor[batch*batch_size:(batch+1)*batch_size])

        # BackwardProp
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Printing in-sample & out-of-sample accuracy
    print('In-sample cross-entropy: ' + str(loss.item()))
    y_pred = model(X_test_tensor)
    print('Out-of-sample accuracy: ' + str((y_pred.argmax(1) == y_test_tensor).sum().item() / 10000))

Running epoch 0
In-sample cross-entropy: 3.6635923385620117
Out-of-sample accuracy: 0.8371
Running epoch 1
In-sample cross-entropy: 1.003132700920105
Out-of-sample accuracy: 0.8534
Running epoch 2
In-sample cross-entropy: 0.6798812747001648
Out-of-sample accuracy: 0.8623
Running epoch 3
In-sample cross-entropy: 0.41081878542900085
Out-of-sample accuracy: 0.8685
Running epoch 4
In-sample cross-entropy: 0.32252317667007446
Out-of-sample accuracy: 0.8597
Running epoch 5
In-sample cross-entropy: 0.28151121735572815
Out-of-sample accuracy: 0.8693
Running epoch 6
In-sample cross-entropy: 0.25253939628601074
Out-of-sample accuracy: 0.8758
Running epoch 7
In-sample cross-entropy: 0.24428600072860718
Out-of-sample accuracy: 0.8726
Running epoch 8
In-sample cross-entropy: 0.20448534190654755
Out-of-sample accuracy: 0.8765
Running epoch 9
In-sample cross-entropy: 0.2105577141046524
Out-of-sample accuracy: 0.8758
Running epoch 10
In-sample cross-entropy: 0.21504290401935577
Out-of-sample accuracy:

There was an improvement of 6 % in the case of convolutional neural networks as compared to neural networks

#Q6.2b

In [27]:
model = nn.Sequential(nn.Conv2d(1,32,5),
        nn.ReLU(),
        nn.Flatten(),
        nn.Linear(32*24*24,32),
        nn.ReLU(),
        nn.Flatten(),
        nn.Linear(32,10))
loss_function = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters())

n_epochs = 100
batch_size = 1000
for epoch in range(n_epochs):
    print('Running epoch ' + str(epoch))
    X_train_tensor, y_train_tensor = shuffle(X_train_tensor, y_train_tensor)

    # Ea. cycle is a loop through all the batches:
    for batch in range(int(60000/batch_size)):

        # ForwardProp
        y_pred = model(X_train_tensor[batch*batch_size:(batch+1)*batch_size])
        loss = loss_function(y_pred, y_train_tensor[batch*batch_size:(batch+1)*batch_size])

        # BackwardProp
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Printing in-sample & out-of-sample accuracy
    print('In-sample cross-entropy: ' + str(loss.item()))
    y_pred = model(X_test_tensor)
    print('Out-of-sample accuracy: ' + str((y_pred.argmax(1) == y_test_tensor).sum().item() / 10000))

Running epoch 0
In-sample cross-entropy: 2.0075087547302246
Out-of-sample accuracy: 0.244
Running epoch 1
In-sample cross-entropy: 1.9130643606185913
Out-of-sample accuracy: 0.2983
Running epoch 2
In-sample cross-entropy: 1.7496153116226196
Out-of-sample accuracy: 0.353
Running epoch 3
In-sample cross-entropy: 1.4522144794464111
Out-of-sample accuracy: 0.4499
Running epoch 4
In-sample cross-entropy: 1.3500432968139648
Out-of-sample accuracy: 0.5325
Running epoch 5
In-sample cross-entropy: 1.31112539768219
Out-of-sample accuracy: 0.5404
Running epoch 6
In-sample cross-entropy: 1.3068054914474487
Out-of-sample accuracy: 0.5415
Running epoch 7
In-sample cross-entropy: 1.1344352960586548
Out-of-sample accuracy: 0.5499
Running epoch 8
In-sample cross-entropy: 1.1256035566329956
Out-of-sample accuracy: 0.5591
Running epoch 9
In-sample cross-entropy: 1.1374834775924683
Out-of-sample accuracy: 0.553
Running epoch 10
In-sample cross-entropy: 1.093110203742981
Out-of-sample accuracy: 0.5565
Runn

There is no significant increase in the accuracy than the 2nd neural network model